artifacts_root : artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  raw_stock_data: artifacts/data_ingestion/raw_data.csv

data_validation:
  root_dir: artifacts/data_validation
  validation_input: artifacts/data_ingestion/raw_data.csv
  num_of_columns: 7
  validation_schema: 
    Date: datetime
    Adj Close: float
    Close: float
    High: float
    Low: float
    Open: float
    Volume: int
  validation_report_path: artifacts/data_validation/validation_report.txt
  validation_output_path: artifacts/data_validation/validated_data.csv

data_transformation:
  root_dir: artifacts/data_transformation
  transformation_input: artifacts/data_validation/validated_data.csv
  transformation_output: artifacts/data_transformation/transformed_data.csv

model_trainer:
  root_dir: artifacts/model_trainer
  training_input: artifacts/data_transformation/transformed_data.csv
  lstm_model: artifacts/model_trainer/lstm_model.keras
  